/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"


/********************   Prog    ********************/
Program make_Prog(ListDef p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog!\n");
        exit(1);
    }
    tmp->kind = is_Prog;
    tmp->u.prog_.listdef_ = p1;
    return tmp;
}/********************   Define    ********************/
Def make_Define(Ident p1, Exp p2)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Define!\n");
        exit(1);
    }
    tmp->kind = is_Define;
    tmp->u.define_.ident_ = p1;
    tmp->u.define_.exp_ = p2;
    return tmp;
}
/********************   Deftype    ********************/
Def make_Deftype(Ident p1, Type p2)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Deftype!\n");
        exit(1);
    }
    tmp->kind = is_Deftype;
    tmp->u.deftype_.ident_ = p1;
    tmp->u.deftype_.type_ = p2;
    return tmp;
}
/********************   Data    ********************/
Def make_Data(UIdent p1, ListDataCon p2)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Data!\n");
        exit(1);
    }
    tmp->kind = is_Data;
    tmp->u.data_.uident_ = p1;
    tmp->u.data_.listdatacon_ = p2;
    return tmp;
}
/********************   DExp    ********************/
Def make_DExp(Exp p1)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating DExp!\n");
        exit(1);
    }
    tmp->kind = is_DExp;
    tmp->u.dexp_.exp_ = p1;
    return tmp;
}/********************   ListDef    ********************/
ListDef make_ListDef(Def p1, ListDef p2)
{
    ListDef tmp = (ListDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListDef!\n");
        exit(1);
    }
    tmp->def_ = p1;
    tmp->listdef_ = p2;
    return tmp;
}/********************   CInt    ********************/
Const make_CInt(Integer p1)
{
    Const tmp = (Const) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CInt!\n");
        exit(1);
    }
    tmp->kind = is_CInt;
    tmp->u.cint_.integer_ = p1;
    return tmp;
}
/********************   CFloat    ********************/
Const make_CFloat(Double p1)
{
    Const tmp = (Const) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CFloat!\n");
        exit(1);
    }
    tmp->kind = is_CFloat;
    tmp->u.cfloat_.double_ = p1;
    return tmp;
}
/********************   CBool    ********************/
Const make_CBool(Boolean p1)
{
    Const tmp = (Const) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CBool!\n");
        exit(1);
    }
    tmp->kind = is_CBool;
    tmp->u.cbool_.boolean_ = p1;
    return tmp;
}/********************   EAdd    ********************/
Exp make_EAdd(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EAdd!\n");
        exit(1);
    }
    tmp->kind = is_EAdd;
    tmp->u.eadd_.exp_1 = p1;
    tmp->u.eadd_.exp_2 = p2;
    return tmp;
}
/********************   EMul    ********************/
Exp make_EMul(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EMul!\n");
        exit(1);
    }
    tmp->kind = is_EMul;
    tmp->u.emul_.exp_1 = p1;
    tmp->u.emul_.exp_2 = p2;
    return tmp;
}
/********************   EConst    ********************/
Exp make_EConst(Const p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EConst!\n");
        exit(1);
    }
    tmp->kind = is_EConst;
    tmp->u.econst_.const_ = p1;
    return tmp;
}
/********************   EVar    ********************/
Exp make_EVar(Ident p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EVar!\n");
        exit(1);
    }
    tmp->kind = is_EVar;
    tmp->u.evar_.ident_ = p1;
    return tmp;
}
/********************   ELam    ********************/
Exp make_ELam(ListIdent p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELam!\n");
        exit(1);
    }
    tmp->kind = is_ELam;
    tmp->u.elam_.listident_ = p1;
    tmp->u.elam_.exp_ = p2;
    return tmp;
}
/********************   EMatch    ********************/
Exp make_EMatch(ListPatMatch p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EMatch!\n");
        exit(1);
    }
    tmp->kind = is_EMatch;
    tmp->u.ematch_.listpatmatch_ = p1;
    return tmp;
}/********************   SPConst    ********************/
SimplePat make_SPConst(Const p1)
{
    SimplePat tmp = (SimplePat) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SPConst!\n");
        exit(1);
    }
    tmp->kind = is_SPConst;
    tmp->u.spconst_.const_ = p1;
    return tmp;
}
/********************   SPIdent    ********************/
SimplePat make_SPIdent(Ident p1)
{
    SimplePat tmp = (SimplePat) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SPIdent!\n");
        exit(1);
    }
    tmp->kind = is_SPIdent;
    tmp->u.spident_.ident_ = p1;
    return tmp;
}/********************   PSimple    ********************/
PatMatch make_PSimple(SimplePat p1, Exp p2)
{
    PatMatch tmp = (PatMatch) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PSimple!\n");
        exit(1);
    }
    tmp->kind = is_PSimple;
    tmp->u.psimple_.simplepat_ = p1;
    tmp->u.psimple_.exp_ = p2;
    return tmp;
}
/********************   PData    ********************/
PatMatch make_PData(Ident p1, ListSimplePat p2, Exp p3)
{
    PatMatch tmp = (PatMatch) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PData!\n");
        exit(1);
    }
    tmp->kind = is_PData;
    tmp->u.pdata_.ident_ = p1;
    tmp->u.pdata_.listsimplepat_ = p2;
    tmp->u.pdata_.exp_ = p3;
    return tmp;
}/********************   ListSimplePat    ********************/
ListSimplePat make_ListSimplePat(SimplePat p1, ListSimplePat p2)
{
    ListSimplePat tmp = (ListSimplePat) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListSimplePat!\n");
        exit(1);
    }
    tmp->simplepat_ = p1;
    tmp->listsimplepat_ = p2;
    return tmp;
}/********************   ListPatMatch    ********************/
ListPatMatch make_ListPatMatch(PatMatch p1, ListPatMatch p2)
{
    ListPatMatch tmp = (ListPatMatch) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListPatMatch!\n");
        exit(1);
    }
    tmp->patmatch_ = p1;
    tmp->listpatmatch_ = p2;
    return tmp;
}/********************   TLam    ********************/
Type make_TLam(Type p1, Type p2)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TLam!\n");
        exit(1);
    }
    tmp->kind = is_TLam;
    tmp->u.tlam_.type_1 = p1;
    tmp->u.tlam_.type_2 = p2;
    return tmp;
}
/********************   TInt    ********************/
Type make_TInt()
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TInt!\n");
        exit(1);
    }
    tmp->kind = is_TInt;
    return tmp;
}
/********************   TBool    ********************/
Type make_TBool()
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TBool!\n");
        exit(1);
    }
    tmp->kind = is_TBool;
    return tmp;
}
/********************   TVar    ********************/
Type make_TVar(Ident p1)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TVar!\n");
        exit(1);
    }
    tmp->kind = is_TVar;
    tmp->u.tvar_.ident_ = p1;
    return tmp;
}/********************   ListIdent    ********************/
ListIdent make_ListIdent(Ident p1, ListIdent p2)
{
    ListIdent tmp = (ListIdent) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListIdent!\n");
        exit(1);
    }
    tmp->ident_ = p1;
    tmp->listident_ = p2;
    return tmp;
}/********************   ListType    ********************/
ListType make_ListType(Type p1, ListType p2)
{
    ListType tmp = (ListType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListType!\n");
        exit(1);
    }
    tmp->type_ = p1;
    tmp->listtype_ = p2;
    return tmp;
}/********************   Cnstr    ********************/
DataCon make_Cnstr(UIdent p1, ListType p2)
{
    DataCon tmp = (DataCon) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Cnstr!\n");
        exit(1);
    }
    tmp->kind = is_Cnstr;
    tmp->u.cnstr_.uident_ = p1;
    tmp->u.cnstr_.listtype_ = p2;
    return tmp;
}/********************   ListDataCon    ********************/
ListDataCon make_ListDataCon(DataCon p1, ListDataCon p2)
{
    ListDataCon tmp = (ListDataCon) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListDataCon!\n");
        exit(1);
    }
    tmp->datacon_ = p1;
    tmp->listdatacon_ = p2;
    return tmp;
}
